sc = StaticScenario(-1, 1, 0);
msa = sc.Car.maxSteeringAngle;
minr = sc.Car.Width / tan(msa);
[tl, to] = ParkingPilot.getTarget(...
    sc.parkingSlot.GetX(), sc.parkingSlot.GetY(),...
    sc.parkingSlot.GetOrientationRadians(), ...
    sc.parkingSlot.Width, sc.parkingSlot.Height,...
    sc.Car.GetX(), sc.Car.GetY(),...
    sc.Car.Width, sc.Car.Height);
[ip, gs, dl, do] = ParkingPilot.tryDirectParking(...
    sc.Car.GetX(), sc.Car.GetY(),...
    sc.Car.GetOrientationRadians(), ...
    tl(1), tl(2), to, 1, minr);
figure;
hold on;
axis([-10 10 -10 10]);
ctrl_mat = getDubinsPath([sc.Car.GetX() sc.Car.GetY() sc.Car.GetOrientationRadians()], [dl(1) dl(2) do], minr);